In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences
sent= ['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### vocabulary

voc_size= 100000

#### One Hot Representation

In [5]:
onehot_repr= [one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[50441, 83447, 14905, 29654], [50441, 83447, 14905, 5227], [50441, 91176, 14905, 13537], [85775, 35729, 74551, 82173, 75740], [85775, 35729, 74551, 82173, 7898], [88624, 50441, 30376, 14905, 94972], [95829, 53089, 2186, 82173]]


##### Word Embedding Representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [12]:
sent_length=8
embedded_docs= pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[    0     0     0     0 50441 83447 14905 29654]
 [    0     0     0     0 50441 83447 14905  5227]
 [    0     0     0     0 50441 91176 14905 13537]
 [    0     0     0 85775 35729 74551 82173 75740]
 [    0     0     0 85775 35729 74551 82173  7898]
 [    0     0     0 88624 50441 30376 14905 94972]
 [    0     0     0     0 95829 53089  2186 82173]]


In [21]:
dim=10

In [22]:
model= Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [23]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             1000000   
Total params: 1,000,000
Trainable params: 1,000,000
Non-trainable params: 0
_________________________________________________________________


In [24]:
print(model.predict(embedded_docs))

[[[-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823
   -0.03594799 -0.01574043 -0.00124868 -0.02599105 -0.04161222]
  [-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823
   -0.03594799 -0.01574043 -0.00124868 -0.02599105 -0.04161222]
  [-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823
   -0.03594799 -0.01574043 -0.00124868 -0.02599105 -0.04161222]
  [-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823
   -0.03594799 -0.01574043 -0.00124868 -0.02599105 -0.04161222]
  [ 0.03474431 -0.0210876  -0.03328892 -0.01452493  0.01834894
   -0.03946313 -0.00627545 -0.01775702 -0.03137134  0.01713112]
  [ 0.02484331  0.00798485  0.01017958 -0.029282    0.03285236
    0.03279364  0.02020596 -0.00485349 -0.02787191  0.02736571]
  [ 0.04646938  0.02044051 -0.0321969  -0.0189193   0.04095525
    0.02803903 -0.02965468 -0.03833822 -0.04415553 -0.04728439]
  [ 0.02369671  0.00386473  0.04287546 -0.02695971  0.00698217
   -0.04836284  0.0170786   0.03447619 -0.012618

In [25]:
embedded_docs[0]

array([    0,     0,     0,     0, 50441, 83447, 14905, 29654])

In [26]:
print(model.predict(embedded_docs)[0])

[[-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823 -0.03594799
  -0.01574043 -0.00124868 -0.02599105 -0.04161222]
 [-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823 -0.03594799
  -0.01574043 -0.00124868 -0.02599105 -0.04161222]
 [-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823 -0.03594799
  -0.01574043 -0.00124868 -0.02599105 -0.04161222]
 [-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823 -0.03594799
  -0.01574043 -0.00124868 -0.02599105 -0.04161222]
 [ 0.03474431 -0.0210876  -0.03328892 -0.01452493  0.01834894 -0.03946313
  -0.00627545 -0.01775702 -0.03137134  0.01713112]
 [ 0.02484331  0.00798485  0.01017958 -0.029282    0.03285236  0.03279364
   0.02020596 -0.00485349 -0.02787191  0.02736571]
 [ 0.04646938  0.02044051 -0.0321969  -0.0189193   0.04095525  0.02803903
  -0.02965468 -0.03833822 -0.04415553 -0.04728439]
 [ 0.02369671  0.00386473  0.04287546 -0.02695971  0.00698217 -0.04836284
   0.0170786   0.03447619 -0.01261874 -0.03813922]]

In [27]:
embedded_docs[4]

array([    0,     0,     0, 85775, 35729, 74551, 82173,  7898])

In [28]:
print(model.predict(embedded_docs)[4])

[[-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823 -0.03594799
  -0.01574043 -0.00124868 -0.02599105 -0.04161222]
 [-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823 -0.03594799
  -0.01574043 -0.00124868 -0.02599105 -0.04161222]
 [-0.01007763 -0.01541362 -0.02927206  0.04130684  0.03939823 -0.03594799
  -0.01574043 -0.00124868 -0.02599105 -0.04161222]
 [ 0.01514195  0.01534709 -0.03172656  0.03515258 -0.04058992 -0.00396596
  -0.00790983  0.02672315 -0.02714186 -0.0342875 ]
 [ 0.0227484  -0.01066375 -0.0279547  -0.00898517  0.02456884  0.00046019
   0.01901105  0.03836802 -0.01677771 -0.01768393]
 [ 0.01158404  0.03764484 -0.04764983 -0.01915603  0.03604602 -0.04430712
   0.04677005 -0.02159836 -0.01886371 -0.04232053]
 [-0.03977547  0.02432802  0.03900665 -0.00084592  0.00868924  0.02976609
  -0.03245465 -0.00138397 -0.01805916  0.02593132]
 [-0.03631828  0.01116939 -0.04612732 -0.04467104  0.02960077  0.04314547
  -0.04390912 -0.02572546  0.04583624 -0.02892454]]